// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlVO0MavLVhTREOIuEwle-JL69Cs_0Wis',
    appId: '1:771423022428:web:a7c55df967a7f65ef62599',
    messagingSenderId: '771423022428',
    projectId: 'testmac-9cab1',
    authDomain: 'testmac-9cab1.firebaseapp.com',
    storageBucket: 'testmac-9cab1.appspot.com',
    measurementId: 'G-MXJTVSGNY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcHi-IwNoY0lwEGc5BApRAPAmy6vsql9E',
    appId: '1:771423022428:android:97ebc71a28ac5cb7f62599',
    messagingSenderId: '771423022428',
    projectId: 'testmac-9cab1',
    storageBucket: 'testmac-9cab1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkDMmq9yhL4Lz0SY1FVANWstyHw3K7njc',
    appId: '1:771423022428:ios:e6c1e8a50faf475cf62599',
    messagingSenderId: '771423022428',
    projectId: 'testmac-9cab1',
    storageBucket: 'testmac-9cab1.appspot.com',
    iosBundleId: 'com.example.firebasetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkDMmq9yhL4Lz0SY1FVANWstyHw3K7njc',
    appId: '1:771423022428:ios:1d984b6c303d32aef62599',
    messagingSenderId: '771423022428',
    projectId: 'testmac-9cab1',
    storageBucket: 'testmac-9cab1.appspot.com',
    iosBundleId: 'com.example.firebasetest.RunnerTests',
  );
}
